orbs:
  cli: circleci/circleci-cli@0.1.1
  orb-tools: circleci/orb-tools@2.0.2

version: 2.1

defaults: &defaults
  executor: cli/default

jobs:
  install-cli:
    <<: *defaults
    steps:
      - cli/install

workflows:
  version: 2
  build:
    jobs:
      - install-cli
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: dist/orb.yml
