orbs:
  cli: circleci/circleci-cli@0.1.1
  orb-tools: circleci/orb-tools@2.0.2

version: 2.1

defaults: &defaults
  executor: cli/default

jobs:
  install-cli:
    <<: *defaults
    steps:
      - cli/install

workflows:
  version: 2
  build:
    jobs:
      - install-cli
      - orb-tools/pack:
          requires:
            - install-cli
          attach-workspace: true
          source-dir: src/
          destination-orb-path: dist/orb.yml
          workspace-path: .
      - orb-tools/publish:
          requires:
            - orb-tools/pack
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only: master
          attach-workspace: true
          orb-path: dist/orb.yml
          orb-ref: ci-tools/npm@dev:$CIRCLE_SHA1
          publish-token-variable: $ORB_PUBLISHING_TOKEN
          validate: false
          checkout: false
